{"name": "name为空，新增失败", "status": "failed", "statusDetails": {"message": "AssertionError", "trace": "self = <testcase.test_department_manage.Test_department_manage object at 0x0000028EE668BBE0>\nenvironment_url = 'http://ihrm-test.itheima.net'\nget_token = {'Authorization': 'Bearer 59519d6b-76e2-4650-86e3-8082a47bcd0d'}\ntitle = 'name为空，新增失败', ask = {'code': 9527, 'name': None}\nexcepted = {'code': 99999, 'message': '请稍后重试', 'status_code': 200, 'success': False}\n\n    @allure.story('新增部门信息-数据驱动测试')\n    @allure.title('{title}')\n    @pytest.mark.usefixtures('re_login')\n    @pytest.mark.parametrize('title, ask, excepted', My_return_data.return_test_data('add_department.yaml'))\n    def test_add_department(self, environment_url, get_token, title, ask, excepted):\n        try:\n            res = Department_Manage().add_department(environment_url, get_token, ask)\n            common_assert(res, excepted)\n        except Exception as e:\n            err = str(res.json()) + '\\n' + str(e)\n            MyLog.error(err)\n>           raise e\n\ntest_department_manage.py:73: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\ntest_department_manage.py:69: in test_add_department\n    common_assert(res, excepted)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nres = <Response [200]>\nexpected = {'code': 99999, 'message': '请稍后重试', 'status_code': 200, 'success': False}\n\n    @allure.step('进行断言')\n    def common_assert(res, expected):\n        '''\n        对响应体进行断言\n        :param res: 请求响应体\n        :param expected: 字典：{success: true， code: 10000， message: '操作成功'， status_code: 200}\n        :return:assert断言\n        '''\n        assert expected.get('status_code') == res.status_code\n>       assert expected.get('code') == res.json().get('code')\nE       AssertionError\n\n..\\utils\\commen_assert.py:13: AssertionError"}, "steps": [{"name": "添加部门", "status": "passed", "parameters": [{"name": "url", "value": "'http://ihrm-test.itheima.net'"}, {"name": "token", "value": "{'Authorization': 'Bearer 59519d6b-76e2-4650-86e3-8082a47bcd0d'}"}, {"name": "add_data", "value": "{'name': None, 'code': 9527}"}], "start": 1632144216419, "stop": 1632144216497}, {"name": "进行断言", "status": "failed", "statusDetails": {"message": "AssertionError\n", "trace": "  File \"E:\\Python\\Python38\\lib\\site-packages\\allure_commons\\_allure.py\", line 172, in impl\n    return func(*a, **kw)\n  File \"D:\\IHRM_project\\utils\\commen_assert.py\", line 13, in common_assert\n    assert expected.get('code') == res.json().get('code')\n"}, "parameters": [{"name": "res", "value": "<Response [200]>"}, {"name": "expected", "value": "{'success': False, 'code': 99999, 'message': '请稍后重试', 'status_code': 200}"}], "start": 1632144216497, "stop": 1632144216497}], "attachments": [{"name": "log", "source": "09fbbb84-ca10-4ee9-947f-c6a14fb31cc9-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "title", "value": "'name为空，新增失败'"}, {"name": "ask", "value": "{'name': None, 'code': 9527}"}, {"name": "excepted", "value": "{'success': False, 'code': 99999, 'message': '请稍后重试', 'status_code': 200}"}], "start": 1632144216419, "stop": 1632144216498, "uuid": "98660fb9-e2aa-44bc-b68d-53c077c34f2d", "historyId": "0ddf814600043989cbd27766d9f07ab7", "testCaseId": "2873253d822787eae1a9ec65ab27d212", "fullName": "testcase.test_department_manage.Test_department_manage#test_add_department", "labels": [{"name": "epic", "value": "基本信息管理模块"}, {"name": "feature", "value": "部门管理模块"}, {"name": "story", "value": "新增部门信息-数据驱动测试"}, {"name": "tag", "value": "@pytest.mark.usefixtures('re_login')"}, {"name": "parentSuite", "value": "testcase"}, {"name": "suite", "value": "test_department_manage"}, {"name": "subSuite", "value": "Test_department_manage"}, {"name": "host", "value": "LAPTOP-LM9EFOVP"}, {"name": "thread", "value": "13272-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcase.test_department_manage"}]}